Repository open-rpc/meta-schema, pull requests merged in 2019-03, with the labels that each got.

#60 feat: typescript it up
  .editorconfig
  .gitignore
  bin/generateTypes.js
  index.js
  package-lock.json
  package.json
  schema.json
  src/index.ts
  src/test.js
  src/types.ts
  tsconfig.json
  tsfmt.json
  tslint.json
Labels: bug

#62 Fix/vendor extensions
  package.json
  schema.json
  src/types.ts
Labels: bug

#64 fix: refactor and remove junk
  schema.json
Labels: enhancement

#67 feat: semantic release
  .circleci/config.yml
  .releaserc
  package.json
Labels: enhancement

#68 feat: add probot
  .github/stale.yml
Labels: enhancement

#70 fix: dependabot ci
  .circleci/config.yml
Labels: bug

#72 fix(methodObject): params is required
  schema.json
Labels: bug

#73 Fix/remove generated types
  .gitignore
  src/types.ts
Labels: enhancement

#80 fix: add server variables
  schema.json
Labels: bug

#87 fix: tests need to require default
  package-lock.json
  package.json
  src/test.js
Labels: bug, dependencies

#84 fix: schema required on contentDescriptorObject
  package-lock.json
  package.json
  schema.json
Labels: bug
