Repository open-rpc/meta-schema, pull requests merged in 2020-10, with the labels that each got.

#288 fix: add eslint ignore pattern for typings
  .eslintrc.js
  package.json
Labels: bug

#292 fix: remove extra meta_schema.go
  meta_schema.go
Labels: bug

#293 fix(package.json): update json schema transpiler version
  package-lock.json
  package.json
Labels: bug

#298 fix: update semantic release transpiler
  package-lock.json
  package.json
Labels: dependencies

#299 Fix/titles and defs
  schema.json
Labels: enhancement

#301 Fix/deref tests
  package.json
  src/test.ts
Labels: enhancement

#315 fix: use updated json-schema-tools meta-schema
  schema.json
Labels: dependencies
